name: Validate Template & Manifest

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:
    inputs:
      svg_path:
        description: 'Path to Template.svg'
        required: false
        default: 'assets/templates/Template.svg'
      manifest_path:
        description: 'Path to template_manifest.json'
        required: false
        default: 'assets/templates/template_manifest.json'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set SVG & Manifest paths
        id: paths
        run: |
          # Defaults (push/PR)
          SVG_PATH="${{ github.event.inputs.svg_path || 'assets/templates/Template.svg' }}"
          MANIFEST_PATH="${{ github.event.inputs.manifest_path || 'assets/templates/template_manifest.json' }}"
          echo "svg=${SVG_PATH}" >> "$GITHUB_OUTPUT"
          echo "manifest=${MANIFEST_PATH}" >> "$GITHUB_OUTPUT"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Sanity check files exist
        run: |
          test -f "${{ steps.paths.outputs.svg }}" || (echo "Missing SVG at ${{ steps.paths.outputs.svg }}" && exit 1)
          test -f "${{ steps.paths.outputs.manifest }}" || (echo "Missing manifest at ${{ steps.paths.outputs.manifest }}" && exit 1)

      - name: Run validator
        run: |
          python backend/scripts/validate_manifest.py "${{ steps.paths.outputs.svg }}" "${{ steps.paths.outputs.manifest }}"
